services:
  mariadb:
    build:
      context: ./requirements/mariadb/.
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
  wordpress:
    build:
      context: ./requirements/wordpress/.
    container_name: wordpress
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - all
    init: true
    env_file:
      - .env
    depends_on:
      - mariadb
  nginx:
    build: 
      context: ./requirements/nginx/.
    container_name: nginx
    ports:
      - '443:443'
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mcarneir/data/mariadb_volume
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mcarneir/data/wordpress_volume

networks:
  all:
    driver: bridge